### ISSUE TITLE
new UML EX1

### ISSUE THREAD

**Issue by Avigdor-Kolonimus** [EngeneringAS/Task2#1]
![uml_ex1](https://user-images.githubusercontent.com/33495117/34130639-442452a8-e451-11e7-8099-f8db263ff9bf.jpg)

**Comment by Avigdor-Kolonimus** [comment]
Shlomi needs to replace UML in the report.

**Comment by sholmiw** [comment]
pic replaced. report will be ready soon.

**Comment by sholmiw** [comment]
done
